# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf0aacef128d95df4e6b1ffc82368d68d0294d1e58b1f182f2f993c9e78b90c32ad2d70caf52af0ee812b4f1559771938d57a2f5dd30b4dfadc015a74e6fda6d

test:
  secret_key_base: d56154c45bfd09263df791756eba1302a70207a22397e7b6a195738254ce1ad41ec441d46bbe5ddce0a8bc3ee116d491fed2fe4c2b5a4f108147e58a64b6ff21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
